### ISSUE TITLE
Call to undefined method TomatoPHP\FilamentTranslations\FilamentTranslationsPlugin::getLanguageSwitcherView()

### ISSUE THREAD

**Issue by streeboga** [tomatophp/filament-translation-component#2]
<img width="756" alt="Снимок экрана 2024-08-08 в 18 19 53" src="https://github.com/user-attachments/assets/4ba7f4b7-904c-4507-8929-a2e15a6f089e">

**Comment by fadymondy** [comment]
fixed on the other package [Filament Translations](https://www.github.com/tomatophp/filament-translations)
